github:
  description: "Apache Tuweni is a set of libraries and other tools to aid development of blockchain and other decentralized software in Java and other JVM languages. It includes a low-level bytes library, serialization and deserialization codecs (e.g. RLP), various cryptography functions and primatives, and lots of other helpful utilities."
  homepage: https://tuweni.apache.org/
  features:
    # Enable issues management
    issues: true
    # Enable project for project management boards
    projects: true
  labels:
    - tuweni
    - blockchain
    - ethereum
    - crypto
    - decentralized
    - securescuttlebutt
  enabled_merge_buttons:
    # enable squash button:
    squash:  true
    # enable merge button:
    merge:   true
    # enable rebase button:
    rebase:  true